name: Build CI

on:
  push:
    branches: [ "master" ]
    paths: &paths
      - "meson.build"
      - "meson.options"
      - "meson_options.txt"
      - "src/**"
      - "man/**"
      - "completion/**"
      - "vim/**"
      - ".github/**"

  pull_request:
    branches: [ "master" ]
    paths: *paths

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: glibc
            container: ""
            install: |
              sudo apt-get update
              sudo apt-get install -y \
                meson ninja-build pkg-config g++ \
                libarchive-dev libacl1-dev attr scdoc
          - name: musl
            container: "alpine:latest"
            install: |
              apk add --no-cache \
                build-base meson ninja pkgconf \
                libarchive-dev acl-dev attr-dev scdoc \
                libarchive-static acl-static attr-static \
                zlib-static zstd-static xz-static bzip2-static lz4-static \
                expat-static openssl-libs-static

        cfg:
          - name: shared
            link_mode: shared
          - name: static
            link_mode: static

    name: ${{ matrix.env.name }} / ${{ matrix.cfg.name }}
    container: ${{ matrix.env.container != '' && matrix.env.container || null }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout libpkgcore
        uses: actions/checkout@v4
        with:
          repository: zeppe-lin/libpkgcore
          path: subprojects/libpkgcore

      - name: Checkout libpkgaudit
        uses: actions/checkout@v4
        with:
          repository: zeppe-lin/libpkgaudit
          path: subprojects/libpkgaudit

      - name: Install build dependencies
        run: ${{ matrix.env.install }}

      - name: Configure pkgutils
        run: |
          meson setup build \
            --buildtype=plain \
            --wrap-mode=nodownload \
            --force-fallback-for=libpkgcore,libpkgaudit \
            --prefix=/usr \
            -Db_lto=false \
            -Db_pie=true \
            -Dlibpkgcore:prefer_static_deps=${{ matrix.cfg.link_mode == 'static' && 'true' || 'false' }} \
            -Dlink_mode=${{ matrix.cfg.link_mode }}

      - name: Build pkgutils
        run: meson compile -C build -v

      - name: Install pkgutils to staging
        run: |
          DESTDIR="$PWD/stage" meson install -C build
